### ISSUE TITLE
tslint needs prettier installed

### ISSUE THREAD

**Issue by teevik** [kata-ai/kata-kit#49]
When i use tslint, it errors with
```
$ tslint -p tsconfig.json
{ Error: Cannot find module 'prettier'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\WebDev\kata-kit\node_modules\tslint-plugin-prettier\rules\prettierRule.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
```

Adding prettier as dependency makes it work, should i create a pull request for that?

**Comment by resir014** [comment]
@teevik Thanks for noticing! This went past us because we've always used to use VSCode for in-IDE linting. 😅 

Feel free to send a pull request.
